# For full config options, check the docs:
#    docs.serverless.com

service: todo-v2-back

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  environment:
    DYNAMODB_TABLE_NAME: ${self:custom.todoTableName}

custom:
  todoTableName: todo-table-${self:provider.stage}
  ##### Uncomment below for local dev
  # dynamodb:
  #   stages:
  #     - dev
  #   start:
  #     migrate: true
  #     port: 8000
  # serverless-offline:
  #   resourceRoutes: true # HTTP proxy

plugins:
  - serverless-iam-roles-per-function
  ##### Uncomment below for local dev
  # - serverless-dynamodb-local
  # - serverless-offline

functions:
  mainHandler:
    handler: index.handler
    name: handler
    memorySize: 128 # mb
    timeout: 5 # seconds
    events:
      - http: ## Get all todos
          path: todos/
          method: GET
      - http: ## Get todos by id
          path: todo/{todoId}
          method: GET
      - http: ## Create todo
          path: todo/
          method: POST
      - http: ## Update todo by todoId
          path: todo/{todoId}
          method: PUT
      - http: ## Delete todo by todoId
          path: todo/{todoId}
          method: DELETE
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - "dynamodb:Scan"
          - "dynamodb:GetItem"
          - "dynamodb:PutItem"
          - "dynamodb:UpdateItem"
          - "dynamodb:DeleteItem"
        Resource: !GetAtt TodoTable.Arn
  

resources:
  Resources:
    TodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.todoTableName}
        AttributeDefinitions:
          - AttributeName: todoId
            AttributeType: S
        KeySchema:
          - AttributeName: todoId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1